# Generated by Django 2.2.7 on 2019-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
