# Generated by Django 2.2.7 on 2019-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
