# Generated by Django 2.2.7 on 2019-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(blank=True),
        ),
    ]
