# Generated by Django 2.2.7 on 2019-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191124_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_cd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
