# Generated by Django 2.2.7 on 2019-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20191127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True),
        ),
    ]
